services:
  - type: web
    name: textile-erp
    env: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        value: textile-erp-render-secret-2024
